### ISSUE TITLE
試しにvueの環境構築を進める

### ISSUE THREAD

**Issue by p238049y** [kokoichi206/awesome-chat-app#5]
### 参考文献
* [Vue3 ハンズオンプロジェクトの作成](https://handson.vuejs-jp.org/create.html)
* [Vite の設定](https://ja.vitejs.dev/config/)
* [Configuring Jest](https://archive.jestjs.io/docs/ja/configuration#globals-object)

**Comment by p238049y** [comment]
### 参考文献
* [Vue3 ハンズオンプロジェクトの作成](https://handson.vuejs-jp.org/create.html)
* [Vite の設定](https://ja.vitejs.dev/config/)
* [Configuring Jest](https://archive.jestjs.io/docs/ja/configuration#globals-object)

**Comment by p238049y** [comment]
Vuetify, jestを追加した

**Comment by Shimpei-GANGAN** [comment]
@p238049y 

## 質問

Vue3 + Vite環境ではなくNuxt3の方が良いかなと思ってますが、Vue3 + Viteでそのまま進めますか。

**Comment by p238049y** [comment]
がんちゃんが整備してくれたのでクローズする
